candida_auris:
  reference_gff: /mnt/db/apollo/variant-typing/candida_auris/GCF_003013715.1.gff
  resistance_variants_csv: files/cauris/resistance_list.csv
other:
  reference_gff: None
  resistance_variants_csv: None