# Testing for pipeline python wrapper and scripts used inside rules

name: Juno_assembly test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {os: ubuntu-latest}
    name: Testing Apollo-variant-typing ${{ matrix.config.os }}

    steps:
      - name: Set up mamba env
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: envs/apollo_variant_typing.yaml
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Test AMR mutation parsing
        shell: bash -l {0}
        run: pytest -v tests/test_amr_mutation_parsing.py